import { createBrowserRouter, Navigate } from "react-router";
import type { RouteObject } from "react-router";
import routes from "~react-pages";
import { MainLayout } from "@/layouts/MainLayout";
import { AuthLayout } from "@/layouts/AuthLayout";
import { ProtectedRoute, PublicRoute } from "@/shared/components/routing";

/**
 * Automatically maps page routes generated by vite-plugin-pages
 * into layout and protection configurations.
 */
const wrapWithLayouts = (generatedRoutes: RouteObject[]): RouteObject[] => {
  const authChildren: RouteObject[] = [];
  const mainChildren: RouteObject[] = [];

  // Index redirect to dashboard
  mainChildren.push({ index: true, element: <Navigate to="/dashboard" replace /> });

  generatedRoutes.forEach((route) => {
    const originalPath = route.path || "";
    const cleanPath = originalPath.toLowerCase().replace("page", "").trim();

    if (cleanPath.includes("login") || cleanPath.includes("register")) {
      authChildren.push(route);
    } else {
      mainChildren.push(route);
    }
  });

  return [
    {
      element: <PublicRoute />,
      children: [
        {
          element: <AuthLayout />,
          children: authChildren,
        },
      ],
    },
    {
      element: <ProtectedRoute />,
      children: [
        {
          element: <MainLayout />,
          children: mainChildren,
        },
      ],
    },
  ];
};

export const router = createBrowserRouter(wrapWithLayouts(routes));
