import { createBrowserRouter, RouteObject, Navigate } from "react-router";
import routes from "~react-pages";
import { MainLayout } from "@/layouts/MainLayout";
import { AuthLayout } from "@/layouts/AuthLayout";

/**
 * Automatically maps flat page routes generated by vite-plugin-pages
 * into layout configurations.
 */
const wrapWithLayouts = (generatedRoutes: RouteObject[]): RouteObject[] => {
  const authPaths = ["/login", "/register"];
  const mainPaths = ["/dashboard", "/settings"];

  const authChildren: RouteObject[] = [];
  const mainChildren: RouteObject[] = [];

  // Index redirect to dashboard
  mainChildren.push({ index: true, element: <Navigate to="/dashboard" replace /> });

  generatedRoutes.forEach((route) => {
    const originalPath = route.path || "";
    // Clean and normalize paths (e.g. DashboardPage -> dashboard)
    const cleanPath = originalPath.toLowerCase().replace("page", "").trim();

    const standardizedRoute = { ...route, path: cleanPath };

    if (authPaths.includes("/" + cleanPath) || cleanPath === "login" || cleanPath === "register") {
      authChildren.push(standardizedRoute);
    } else if (
      mainPaths.includes("/" + cleanPath) ||
      cleanPath === "dashboard" ||
      cleanPath === "settings"
    ) {
      mainChildren.push(standardizedRoute);
    }
  });

  return [
    {
      element: <AuthLayout />,
      children: authChildren,
    },
    {
      element: <MainLayout />,
      children: mainChildren,
    },
  ];
};

export const router = createBrowserRouter(wrapWithLayouts(routes));
